a = input('digite algo:')
print('O tipo primitivo desse valor é {}'.format(type(a)))
print('só tem espaços?',a.isspace())
print('é só um número?',a.isnumeric())
print('é alfabético?',a.isalpha())
print('é alfanumérico?',a.isalnum())
print('está em maiúsculo?',a.isupper())
print('está em minúsculo?',a.islower())
print('está capitalizada?',a.istitle())
