n = int(input('Escolha um número inteiro para saber sua tabuada: '))
print('o número escolhido foi {}:'.format(n))
print(n*1)
print(n*2)
print(n*3)
print(n*4)
print(n*5)
print(n*6)
print(n*7)
print(n*8)
print(n*9)
print(n*10)
#for c in range(1, 10):
#    print('{} x {} = {}'.format(n, c, n*c))
